name: Build and Release IW7-Mod

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "cfg/**"
      - "data/**"
      - "deps/**"
      - "installer/**"
      - "src/**"

    # paths-ignore:
    #   - ".gitea"
    #   - ".vscode"
    #   - "assets"
    #   - "tools"
    #   - ".gitignore"
    #   - ".gitmodules"
    #   - "build.bat"
    #   - "generate.bat"
    #   - "premake5.lua"
    #   - "README.md"

  # tags:
  #   - "*" # Trigger the workflow when any tag is pushed. This causes an infinite loop with my janky curl method
  # schedule:
  # - cron: "0 0 * * 0"  # Runs weekly on Sunday at midnight UTC
  # - cron: "*/1 * * * *"  # Runs every 1 minute
  # - cron: "0 0 0 0 0"
jobs:
  build:
    name: Compile and Stage
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Release
    steps:
      - name: Check Out Files
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          lfs: false # Note: If LFS ever starts getting used during builds, switch this to true!

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Generate Project
        run: tools/premake5 vs2022

      - name: Set Up Problem Matching
        uses: ammaraskar/msvc-problem-matcher@master

      - name: Build Release Binary
        run: msbuild /m /v:minimal /p:Configuration=${{matrix.configuration}} /p:Platform=x64 build/iw7-mod.sln

      - name: Compile Installer
        run: |
          ./installer/compile.bat

      - name: Stage Release
        run: |
          mkdir staging
          mv data/cdata staging/iw7-mod
          mv "cfg/!start_client.bat" staging/.
          mv cfg/dvars.json staging/iw7-mod/.
          mv build/bin/x64/${{matrix.configuration}}/iw7-mod.exe staging/.
          mv build/bin/x64/${{matrix.configuration}}/tlsdll.dll staging/.
          mkdir ./release-artifacts

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iw7-installer
          compression-level: 9
          path: |
            installer/build/iw7-installer.exe

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod
          compression-level: 9
          path: |
            staging/*

      - name: Upload Server Configuration Artifact
        uses: actions/upload-artifact@v3
        with:
          name: IW7DedicatedConfigs
          compression-level: 9
          path: |
            cfg/*

      - name: Upload Standalone Release Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod-${{matrix.configuration}}-standalone
          compression-level: 9
          path: |
            staging/iw7-mod.exe

      - name: Upload Debug Release Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iw7-mod-${{matrix.configuration}}-debug-binary
          path: |
            build/bin/x64/${{matrix.configuration}}/iw7-mod.pdb

  Release:
    needs: build
    name: Publish Release Assets
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download ZIP Artifact
        uses: actions/download-artifact@v3
        with:
          name: iw7-mod
          path: ./release-artifacts/iw7-mod

      - name: Download Installer Artifact
        uses: actions/download-artifact@v3
        with:
          name: iw7-installer
          path: ./release-artifacts

      - name: Download Debug Release Binary Artifact
        uses: actions/download-artifact@v3
        with:
          name: iw7-mod-Release-debug-binary
          path: ./release-artifacts

      - name: Download Server Configuration Artifact
        uses: actions/download-artifact@v3
        with:
          name: IW7DedicatedConfigs
          path: ./release-artifacts/IW7DedicatedConfigs

      - name: Compress Artifacts
        run: |
          powershell -Command 'Compress-Archive -Path ./release-artifacts/iw7-mod/* -DestinationPath ./release-artifacts/iw7-mod.zip -Force'
          powershell -Command 'Compress-Archive -Path ./release-artifacts/IW7DedicatedConfigs/* -DestinationPath ./release-artifacts/IW7DedicatedConfigs.zip -Force'

        # This is the jankiest shit I've ever done, but it works
      - name: Delete Tag
        run: |
          curl -X "DELETE" "https://git.rimmyscorner.com/api/v1/repos/Rim/iw7-mod/tags/latest" -H "authorization: token ${{ secrets.TOKEN }}"

      - name: Delete Release
        run: |
          curl -X "DELETE" "https://git.rimmyscorner.com/api/v1/repos/Rim/iw7-mod/releases/tags/latest" -H "authorization: token ${{ secrets.TOKEN }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: latest
          release_name: IW7-Mod
          body: |
            ### Steam Verification has been removed. You do **<u>NOT</u>** need to own the game in order to play.
            - [Where can I get the game?](https://git.rimmyscorner.com/Rim/iw7-mod#where-can-i-get-the-game)
            - [Instructions](https://git.rimmyscorner.com/Rim/iw7-mod#instructions)

            Compiled by [Actions Runner](https://git.rimmyscorner.com/Rim/iw7-mod/actions)

            ## Disclaimer<a id="disclaimer"></a>

            We do not condone piracy of any kind. Asking for, providing, or discussing illegal download links is not allowed in our communities.

            <a id="downloads"></a>
          draft: false
          prerelease: false

      # This man shogo82148 really saved my sanity after HOURS of screwing with this using the official unmaintained repo...
      - name: Release ZIP
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-mod.zip
          asset_name: iw7-mod.zip
          asset_content_type: application/octet-stream

      - name: Release Debug Binary
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-mod.pdb
          asset_name: iw7-mod.pdb
          asset_content_type: application/octet-stream

      - name: Release Installer
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/iw7-installer.exe
          asset_name: iw7-installer.exe
          asset_content_type: application/octet-stream

      - name: Release Server Configuration
        uses: shogo82148/actions-upload-release-asset@v1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release-artifacts/IW7DedicatedConfigs.zip
          asset_name: IW7DedicatedConfigs.zip
          asset_content_type: application/octet-stream
